-- 1.

SELECT VACATION.ID, CONTENT.PRICE
FROM VACATION JOIN CONTENT
	ON VACATION.ID = CONTENT.VACATIONID
WHERE VACATION.COUNTRY LIKE 'M%A%IJA'

-- 2.

SELECT HOTEL
FROM TRANSPORT JOIN PACKAGE
	ON TRANSPORT.ID = PACKAGE.ID
GROUP BY HOTEL
HAVING COUNT(DISTINCT TRANSPORT.TRANSPORT) > 3

-- 3.

WITH VACATIONCITY AS
(SELECT VACATIONID, COUNT(DISTINCT CITY)
FROM CONTENT JOIN PACKAGE
	ON CONTENT.PACKAGEID=PACKAGE.ID
GROUP BY VACATIONID)

SELECT VACATION.*
FROM VACATION JOIN VACATIONCITY 
	ON VACATION.ID = VACATIONCITY.VACATIONID
WHERE VACATIONCITY.COUNT > 2

-- 4.1

-- IF THERE ARE MORE THAN 1 VACATIONS WITH THE SAME MAXIMUM, THEN THE SOLUTION WILL NOT GIVE US THE CORRECT RESULTS

WITH VACATIONTRANSPORT AS
(SELECT VACID, COUNT(DISTINCT TRANSPORT) TRANSPORT_COUNT
FROM CONTENT C JOIN TRANSPORT T
	ON C.PACKAGEID=T.PACKAGEID
GROUP BY VACID)

SELECT TOP 1 V.*
FROM VACATION V JOIN VACATIONTRANSPORT VT
	ON V.ID = VT.ID
ORDER BY TRANSPORT_COUNT DESC

-- IN THAT CASE WE CAN USE THIS SOLUTION

WITH VACATIONTRASPORT AS
(SELECT C.VACID, COUNT(DISTINCT TRANSPORT) TRANSPORT_COUNT
FROM CONTENT C JOIN TRANSPORT T
	ON C.PACKAGEID=T.PACKAGEID
GROUP BY C.VACID)

SELECT V.*
FROM VACATION V JOIN VACATIONTRANSPORT VT
	ON V.VACID=VT.VACID
WHERE VT.TRANSPORT_COUNT = (SELECT MAX(TRANSPORT_COUNT)
				FROM VACATIONTRANSPORT)

-- THIRD SOLUTION

SELECT VACID, COUNT(DISTINCT TRANSPORT) TRANSPORT_COUNT
INTO £VACATIONTRANSPORT
FROM CONTENT C JOIN TRANSPORT T 
	ON C.PACKAGEID=T.PACKAGEID
GROUP BY VACID

SELECT MAX(TRANSPORT_COUNT) MAKS
INTO #MAXTRANSPORT 
FROM #VACATIONTRANSPORT

WITH TARGETVACATION AS
(SELECT VACID
FROM #VACATIONTRANSPORT VT JOIN #MAXTRANSPORT MT
	ON VT.TRANSPORTNO = MT.MAKS)

SELECT V.*
FROM VACATION V JOIN TARGETVACATION TV
	ON V.VACID=TV.VACID

-- 5.	

WITH PROFIT AS
(SELECT EMPID, SUM(PERCENT*PRICE) TOTAL
FROM GUIDANCE G JOIN VACATION V 
	ON G.VACATIONID=V.VACATIONID JOIN CONTENT C
		ON V.VACATIONID=C.VACATIONID
WHERE START_DATE BETWEEN '2017-07-01' AND '2017-07-31'
GROUP BY EMPID)

SELECT EMPID
FROM PROFIT
WHERE TOTAL >  (SELECT AVG(TOTAL)
		FROM PROFIT)


-- FIND THE GUIDES THAT HAD AVERAGE PROFIT PER VACATION BIGGER THAN THE
-- AVERAGE PROFIT PER GUIDE IN JULY 2017

WITH VACPROFIT AS
(SELECT EMPID, VACID, SUM(PERCENT*PRICE) TOTAL
FROM GUIDANCE G JOIN VACATION V 
	ON G.VACID=V.VACID JOIN CONTENT C
		ON V.VACID=C.VACID
WHERE START_DATE BETWEEN '2017-07-01' AND '2017-07-31'
GROUP BY EMPID, VACID)

SELECT EMPID, AVG(TOTAL) AVRG
INTO #AVRGPROFIT
FROM VACPROFIT
GROUP BY EMPID

WITH PROFIT AS
(SELECT EMPID, SUM(PERCENT*PRICE) TOTAL
FROM GUIDANCE G JOIN VACATION V 
	ON G.VACID=V.VACID JOIN CONTENT C
		ON V.VACID=C.VACID
WHERE START_DATE BETWEEN '2017-07-01' AND '2017-07-31'
GROUP BY EMPID)

SELECT EMPID
FROM #AVRGPROFIT
WHERE AVRG > (SELECT AVG(TOTAL)
		FROM PROFIT)


















